# tasks file for 03-down-list-vm-esx (STOP)

- name: Déboguer les identifiants ESX
  ansible.builtin.debug:
    msg: |
      ESX1 = {{ esx1_hostname }} / {{ esx1_username }} / {{ '*' * (esx1_password | length) }}
      ESX2 = {{ esx2_hostname }} / {{ esx2_username }} / {{ '*' * (esx2_password | length) }}

- name: Vérifier que les variables sensibles sont définies pour ESX1
  ansible.builtin.assert:
    that:
      - esx1_hostname != 'CHANGEMOI'
      - esx1_username != 'CHANGEMOI'
      - esx1_password != 'CHANGEMOI'
    fail_msg: "Variables ESX1 non définies correctement."

- name: Vérifier que les variables sensibles sont définies pour ESX2
  ansible.builtin.assert:
    that:
      - esx2_hostname != 'CHANGEMOI'
      - esx2_username != 'CHANGEMOI'
      - esx2_password != 'CHANGEMOI'
    fail_msg: "Variables ESX2 non définies correctement."

- name: Récupérer les VMs sur ESX1
  community.vmware.vmware_vm_info:
    hostname: "{{ esx1_hostname }}"
    username: "{{ esx1_username }}"
    password: "{{ esx1_password }}"
    validate_certs: "{{ esx1_validate_certs | default(false) }}"
  register: vms_esx1

- name: Récupérer les VMs sur ESX2
  community.vmware.vmware_vm_info:
    hostname: "{{ esx2_hostname }}"
    username: "{{ esx2_username }}"
    password: "{{ esx2_password }}"
    validate_certs: "{{ esx2_validate_certs | default(false) }}"
  register: vms_esx2

- name: Fusionner les deux listes de VMs
  ansible.builtin.set_fact:
    all_vms: "{{ (vms_esx1.virtual_machines | default([])) + (vms_esx2.virtual_machines | default([])) }}"

- name: Extraire les VMs à ARRÊTER depuis l'inventaire
  ansible.builtin.set_fact:
    target_vms: >-
      {{ all_vms
         | selectattr('guest_name', 'defined')
         | selectattr('guest_name', 'in', groups['all'])
         | list }}

- name: Afficher les VMs ciblées
  ansible.builtin.debug:
    var: target_vms

# Garder uniquement celles qui sont allumées
- name: Filtrer les VMs allumées par hôte
  ansible.builtin.set_fact:
    targets_esx1_on: "{{ target_vms
                         | selectattr('esxi_hostname', 'search', '(?i)\\besx01\\b')
                         | selectattr('power_state', 'equalto', 'poweredOn') | list }}"
    targets_esx2_on: "{{ target_vms
                         | selectattr('esxi_hostname', 'search', '(?i)\\besx02\\b')
                         | selectattr('power_state', 'equalto', 'poweredOn') | list }}"

- name: Debug tailles des listes allumées
  ansible.builtin.debug:
    msg: |
      ESX1 ON -> {{ targets_esx1_on | length }} VMs
      ESX2 ON -> {{ targets_esx2_on | length }} VMs

# 1) Arrêt invité (gracieux) ESX01
- name: ESX01 - shutdown-guest
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ esx1_hostname }}"
    username: "{{ esx1_username }}"
    password: "{{ esx1_password }}"
    validate_certs: "{{ esx1_validate_certs | default(false) }}"
    uuid: "{{ item.uuid }}"
    state: shutdown-guest
    state_change_timeout: 120
  loop: "{{ targets_esx1_on }}"
  when: targets_esx1_on | length > 0
  register: shutdown_esx1
  failed_when: false

# 1) Arrêt invité (gracieux) ESX02
- name: ESX02 - shutdown-guest
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ esx2_hostname }}"
    username: "{{ esx2_username }}"
    password: "{{ esx2_password }}"
    validate_certs: "{{ esx2_validate_certs | default(false) }}"
    uuid: "{{ item.uuid }}"
    state: shutdown-guest
    state_change_timeout: 120
  loop: "{{ targets_esx2_on }}"
  when: targets_esx2_on | length > 0
  register: shutdown_esx2
  failed_when: false

# 2) Forçage si encore allumées (sécurité : on force sur tout le lot ciblé)
- name: ESX01 - power-off forcé si nécessaire
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ esx1_hostname }}"
    username: "{{ esx1_username }}"
    password: "{{ esx1_password }}"
    validate_certs: "{{ esx1_validate_certs | default(false) }}"
    uuid: "{{ item.uuid }}"
    state: powered-off
    force: true
  loop: "{{ targets_esx1_on }}"
  when: targets_esx1_on | length > 0
  register: forced_esx1
  failed_when: false

- name: ESX02 - power-off forcé si nécessaire
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ esx2_hostname }}"
    username: "{{ esx2_username }}"
    password: "{{ esx2_password }}"
    validate_certs: "{{ esx2_validate_certs | default(false) }}"
    uuid: "{{ item.uuid }}"
    state: powered-off
    force: true
  loop: "{{ targets_esx2_on }}"
  when: targets_esx2_on | length > 0
  register: forced_esx2
  failed_when: false

# 3) Résumé
- name: Résumé arrêts ESX01
  ansible.builtin.debug:
    msg:
      shutdown_guest: "{{ (shutdown_esx1.results | default([])) | map(attribute='item.guest_name') | list }}"
      forced_off:     "{{ (forced_esx1.results   | default([])) | map(attribute='item.guest_name') | list }}"

- name: Résumé arrêts ESX02
  ansible.builtin.debug:
    msg:
      shutdown_guest: "{{ (shutdown_esx2.results | default([])) | map(attribute='item.guest_name') | list }}"
      forced_off:     "{{ (forced_esx2.results   | default([])) | map(attribute='item.guest_name') | list }}"
